ktor {
  deployment {
    port = 8080
    watch = [ classes ]
  }

  application {
    modules = [ com.example.ApplicationKt.module ]
  }
}

app {
  dbPath = "data/corp-search.db"
  jwt {
    issuer = "corp-search"
    audience = "corp-search-users"
    realm = "corp-search"
    secret = "CHANGE_ME_SUPER_SECRET_32+_CHARS"
    expiresSeconds = 86400
  }
  admin {
    email = "admin@local"
    password = "admin12345"
  }
}
